// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl9vi8zhafsJJ_K-82JQB0YMAohmeqvVw',
    appId: '1:799100120755:web:0bea999f7e4d6aa98f0ac6',
    messagingSenderId: '799100120755',
    projectId: 'logindemo-26a4f',
    authDomain: 'logindemo-26a4f.firebaseapp.com',
    databaseURL: 'https://logindemo-26a4f.firebaseio.com',
    storageBucket: 'logindemo-26a4f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaeb2YCLpjanv0Hv9LUmTVpMM6gtp7ebk',
    appId: '1:799100120755:android:a8aeb79c910a1e248f0ac6',
    messagingSenderId: '799100120755',
    projectId: 'logindemo-26a4f',
    databaseURL: 'https://logindemo-26a4f.firebaseio.com',
    storageBucket: 'logindemo-26a4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLu3kJNqc6KEWkk2gfTxPBrF4p5K1G8J0',
    appId: '1:799100120755:ios:2fa6d25a73c5c2fa8f0ac6',
    messagingSenderId: '799100120755',
    projectId: 'logindemo-26a4f',
    databaseURL: 'https://logindemo-26a4f.firebaseio.com',
    storageBucket: 'logindemo-26a4f.appspot.com',
    iosClientId: '799100120755-lfe6ou7p3qf5baurtg1nv83j7dr9pnco.apps.googleusercontent.com',
    iosBundleId: 'com.example.bibletiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLu3kJNqc6KEWkk2gfTxPBrF4p5K1G8J0',
    appId: '1:799100120755:ios:2fa6d25a73c5c2fa8f0ac6',
    messagingSenderId: '799100120755',
    projectId: 'logindemo-26a4f',
    databaseURL: 'https://logindemo-26a4f.firebaseio.com',
    storageBucket: 'logindemo-26a4f.appspot.com',
    iosClientId: '799100120755-lfe6ou7p3qf5baurtg1nv83j7dr9pnco.apps.googleusercontent.com',
    iosBundleId: 'com.example.bibletiles',
  );
}
